title: VC火神-6
subtitle: 
description:
author: vchs6
language: zh-CN
TimeZone: Asia/Shanghai
Encoding: utf-8

BaseURL: https://vchs6.github.io
permalink: /:year/:month/:day/:title

lsi: true

enable_coderay: true

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
